# Generated by Django 3.2.9 on 2021-12-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_address', models.CharField(max_length=40)),
                ('cli_comment', models.CharField(max_length=40)),
            ],
        ),
    ]
