# Generated by Django 3.2.9 on 2021-12-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='customer_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
    ]
