# Generated by Django 3.2.9 on 2021-12-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.IntegerField()),
                ('pro_name', models.CharField(max_length=25)),
                ('pro_type', models.CharField(max_length=25)),
            ],
        ),
    ]
